#!/usr/bin/env python3
"""
Format converter from Augmentoolkit ShareGPT format to MLX messages format.

This script converts the conversation data generated by Augmentoolkit 
(in ShareGPT format) to the format expected by MLX for fine-tuning.
"""

import json
import argparse
from pathlib import Path
from typing import Dict, List, Any


def convert_sharegpt_to_mlx(conversation: Dict[str, Any]) -> Dict[str, Any]:
    """
    Convert a single conversation from ShareGPT format to MLX format.
    
    Args:
        conversation: ShareGPT format conversation with 'conversations' key
        
    Returns:
        MLX format conversation with 'messages' key
    """
    if 'conversations' not in conversation:
        raise ValueError("Invalid ShareGPT format: missing 'conversations' key")
    
    messages = []
    for msg in conversation['conversations']:
        # Map ShareGPT roles to MLX roles
        role_mapping = {
            'system': 'system',
            'human': 'user', 
            'gpt': 'assistant'
        }
        
        if 'from' not in msg or 'value' not in msg:
            continue  # Skip malformed messages
            
        mlx_role = role_mapping.get(msg['from'])
        if mlx_role is None:
            continue  # Skip unknown roles
            
        messages.append({
            'role': mlx_role,
            'content': msg['value']
        })
    
    return {'messages': messages}


def process_augmentoolkit_output(input_file: Path, output_file: Path, 
                                train_ratio: float = 0.9) -> None:
    """
    Process Augmentoolkit output file and create MLX training files.
    
    Args:
        input_file: Path to Augmentoolkit output JSONL file
        output_file: Base path for output files (will create .train.jsonl and .valid.jsonl)
        train_ratio: Ratio of data to use for training vs validation
    """
    conversations = []
    
    # Read Augmentoolkit output
    with open(input_file, 'r', encoding='utf-8') as f:
        for line in f:
            if line.strip():
                try:
                    conv = json.loads(line)
                    mlx_conv = convert_sharegpt_to_mlx(conv)
                    if mlx_conv['messages']:  # Only include non-empty conversations
                        conversations.append(mlx_conv)
                except json.JSONDecodeError as e:
                    print(f"Warning: Skipping malformed JSON line: {e}")
                except ValueError as e:
                    print(f"Warning: Skipping invalid conversation: {e}")
    
    if not conversations:
        raise ValueError("No valid conversations found in input file")
    
    # Split into train/validation
    split_point = int(len(conversations) * train_ratio)
    train_data = conversations[:split_point]
    valid_data = conversations[split_point:]
    
    # Write training data
    train_file = output_file.parent / f"{output_file.stem}.train.jsonl"
    with open(train_file, 'w', encoding='utf-8') as f:
        for conv in train_data:
            f.write(json.dumps(conv, ensure_ascii=False) + '\n')
    
    # Write validation data
    valid_file = output_file.parent / f"{output_file.stem}.valid.jsonl"
    with open(valid_file, 'w', encoding='utf-8') as f:
        for conv in valid_data:
            f.write(json.dumps(conv, ensure_ascii=False) + '\n')
    
    print(f"Converted {len(conversations)} conversations:")
    print(f"  Training: {len(train_data)} conversations → {train_file}")
    print(f"  Validation: {len(valid_data)} conversations → {valid_file}")


def main():
    parser = argparse.ArgumentParser(description="Convert Augmentoolkit output to MLX format")
    parser.add_argument("input_file", type=Path, 
                       help="Path to Augmentoolkit output JSONL file")
    parser.add_argument("output_base", type=Path,
                       help="Base path for output files (will create .train.jsonl and .valid.jsonl)")
    parser.add_argument("--train-ratio", type=float, default=0.9,
                       help="Ratio of data to use for training (default: 0.9)")
    
    args = parser.parse_args()
    
    if not args.input_file.exists():
        print(f"Error: Input file {args.input_file} does not exist")
        return 1
    
    try:
        process_augmentoolkit_output(args.input_file, args.output_base, args.train_ratio)
        print("Conversion completed successfully!")
        return 0
    except Exception as e:
        print(f"Error during conversion: {e}")
        return 1


if __name__ == "__main__":
    exit(main())