print("Repository Structure:")
print("augmentoolkit-mlx-pipeline/")
print("  submodules/")
print("    augmentoolkit/ (data generation)")
print("    mlx-tuning-fork/ (enhanced MLX training)")
print("  converters/")
print("    augmentoolkit_to_mlx.py (format conversion)")
print("  pipeline/")
print("    orchestrator.py (end-to-end automation)")
print("  configs/")
print("    pipeline.yaml (unified config)")

print("\nData Flow:")
print("1. Raw text → Augmentoolkit → ShareGPT format")
print("2. ShareGPT → Converter → MLX messages format") 
print("3. MLX format → MLX-tuning-fork → LoRA training")
print("4. Training → Model fusion → Deployable MLX model")

print("\nFormat Conversion:")
print("Augmentoolkit: {'from': 'system', 'value': '...'}")
print("MLX:           {'role': 'system', 'content': '...'}")
print("Augmentoolkit: {'from': 'human', 'value': '...'}")
print("MLX:           {'role': 'user', 'content': '...'}")
print("Augmentoolkit: {'from': 'gpt', 'value': '...'}")
print("MLX:           {'role': 'assistant', 'content': '...'}")